wandb_version: 1

batch_size:
  desc: Number of training examples in a mini-batch
  value: 8
classes:
  desc: number of classes
  value: 37
data_dir:
  desc: Raw image directory
  value: /home/l2k/l2k/cosmic_3/optimized
data_suffix:
  desc: file extension of raw images
  value: .png
epochs:
  desc: Number of epochs in training
  value: 250
label_dir:
  desc: Label directory
  value: /home/l2k/l2k/cosmic_3/labels
label_suffix:
  desc: file extension of segmentation labels
  value: .png
model_name:
  desc: Type of model
  value: AtrousFCN_Resnet50_16s
test_file_path:
  desc: List of test files
  value: /home/l2k/l2k/cosmic_3/test.txt
train_file_path:
  desc: List of training data files
  value: /home/l2k/l2k/cosmic_3/train.txt
val_file_path:
  desc: List of validation files
  value: /home/l2k/l2k/cosmic_3/val.txt
